### ISSUE TITLE
I get a 'specific module could not be found' error? Help? 

### ISSUE THREAD

**Issue by KarmaMole** [lllyasviel/Omost#113]
Traceback (most recent call last):
  File "C:\Stable Diffusion Engines\Omost\gradio_app.py", line 6, in <module>
    import lib_omost.memory_management as memory_management
  File "C:\Stable Diffusion Engines\Omost\lib_omost\memory_management.py", line 1, in <module>
    import torch
  File "C:\Users\Omar\.conda\envs\omost\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Omar\.conda\envs\omost\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by DenOfEquity** [comment]
I had the same issue - due to missing a dependency for **fbgemm.dll**. Solution I used was to install updated MS VC++ redistributable.
Go to https://visualstudio.microsoft.com/visual-cpp-build-tools/, then Download Build Tools.
Run it, go to *Individual components* tab, find `MSVC v143 -VS 2022 C++ x64/x86 Build tools (latest)` and install.
More discussion and alternative options: https://github.com/pytorch/pytorch/issues/131662
