### ISSUE TITLE
运行python gradio_app.py时报错

### ISSUE THREAD

**Issue by HazeBlue** [lllyasviel/Omost#124]
Traceback (most recent call last):
  File "H:\Omost\gradio_app.py", line 26, in <module>
    from diffusers import AutoencoderKL, UNet2DConditionModel
  File "H:\conda\envs\omost\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "H:\conda\envs\omost\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "H:\conda\envs\omost\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (H:\conda\envs\omost\lib\site-packages\huggingface_hub\__init__.py)
这个是啥问题
![雾霾蓝先生_2024-11-14_18-17-34](https://github.com/user-attachments/assets/327cc42d-6355-4eeb-a8ae-2451e9758acb)

**Comment by ChantMyZeal** [comment]
maybe you can try: pip install --upgrade diffusers

**Comment by HazeBlue** [comment]
> 也许你可以尝试：pip install --upgrade spreaders

Thanks bro, it worked.

**Comment by HazeBlue** [comment]
> maybe you can try: pip install --upgrade diffusers
![雾霾蓝先生_2024-11-20_23-21-43](https://github.com/user-attachments/assets/22c44103-2c61-4fd8-bbc1-75549e69d0c4)

**Comment by ht2756** [comment]
pip install --upgrade diffusers

**Comment by GawainProdigy** [comment]
Same issue. Upgrading diffusers does not help.

(tutorial-env) H:\olmost\Omost>python gradio_app.py
Traceback (most recent call last):
  File "H:\olmost\Omost\gradio_app.py", line 26, in <module>
    from diffusers import AutoencoderKL, UNet2DConditionModel
  File "H:\olmost\Omost\tutorial-env\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "H:\olmost\Omost\tutorial-env\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "H:\olmost\Omost\tutorial-env\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (H:\olmost\Omost\tutorial-env\Lib\site-packages\huggingface_hub\__init__.py)

Tried to get coding help from various artificial intelligence. Scoured the internet. Tried all the fixes thrown at me. Did several fresh installs. On different drives. Can't figure out what's going on here. Please help.

**Comment by ChantMyZeal** [comment]
it seems that huggingface_hub 0.26 removes 'cached_download', maybe you can reinstall huggingface_hub<=0.25.2

**Comment by GawainProdigy** [comment]
@ChantMyZeal: In fact, you are correct.  I've seen my same issue bandied about, even in different projects and on Reddit. And, you have provided the solution. I want to personally say thank you to you, because it's Christmas and this is a wonderful Christmas present.

Further, I hope our interchange helps other people having this issue resolved theirs as well so they can try this very ingenious application so generously shared under the auspices of lllyasviel.  

Or, more colloquially: thanks a lot. Cheers mate, and have a good one.

**Comment by Qxy0happy** [comment]
Huggingface_hub的版本高了，降一下版本试试

**Comment by EladWarshawsky** [comment]
try my requirements.txt from my pull request in a venv

**Comment by 3runSmiNt** [comment]
pip uninstall gradio
pip install gradio==4.0.0
pip uninstall peft
pip install peft==0.13.0
pip uninstall huggingface_hub
pip install huggingface_hub==0.24.0
