### ISSUE TITLE
I installed Triton 2.0.0 and Omost would not start.

### ISSUE THREAD

**Issue by Torcelllo** [lllyasviel/Omost#16]
I used this file
triton-2.0.0-cp310-cp310-win_amd64.whl

As far as Omost goes, it says it is the 'wrong' version of Triton
but goes without specifying the correct version?!

**Comment by Torcelllo** [comment]
X:\Omost>python gradio_app.py
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.0+cu118 with CUDA 1108 (you have 2.3.0+cu121)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: DLL load failed while importing libtriton: The specified module could not be found.
2024-06-01 16:29:40.558793: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

X:\Omost\lib_omost\pipeline.py:64: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  alphas_cumprod = torch.tensor(np.cumprod(alphas, axis=0), dtype=torch.float32)
Unload to CPU: CLIPTextModel
Unload to CPU: UNet2DConditionModel
Unload to CPU: AutoencoderKL
Unload to CPU: CLIPTextModel
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Traceback (most recent call last):
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1535, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\integrations\bitsandbytes.py", line 13, in <module>
    import bitsandbytes as bnb
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__init__.py", line 15, in <module>
    from .nn import modules
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\nn\__init__.py", line 17, in <module>
    from .triton_based_modules import (
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\nn\triton_based_modules.py", line 6, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\triton\dequantize_rowwise.py", line 12, in <module>
    import triton
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\triton\__init__.py", line 13, in <module>
    from . import language
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\triton\language\__init__.py", line 2, in <module>
    from . import core, extern, libdevice, random
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\triton\language\core.py", line 1141, in <module>
    def abs(x):
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\triton\runtime\jit.py", line 386, in jit
    return JITFunction(args[0], **kwargs)
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\triton\runtime\jit.py", line 315, in __init__
    self.run = self._make_launcher()
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\triton\runtime\jit.py", line 282, in _make_launcher
    scope = {"version_key": version_key(), "get_cuda_stream": get_cuda_stream,
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\triton\runtime\jit.py", line 82, in version_key
    with open(triton._C.libtriton.__file__, "rb") as f:
AttributeError: partially initialized module 'triton' has no attribute '_C' (most likely due to a circular import)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "X:\Omost\gradio_app.py", line 75, in <module>
    llm_model = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 3640, in from_pretrained
    hf_quantizer.preprocess_model(
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\quantizers\base.py", line 182, in preprocess_model
    return self._process_model_before_weight_loading(model, **kwargs)
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\quantizers\quantizer_bnb_4bit.py", line 259, in _process_model_before_weight_loading
    from ..integrations import get_keys_to_not_convert, replace_with_bnb_linear
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1525, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1537, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.integrations.bitsandbytes because of the following error (look up to see its traceback):
partially initialized module 'triton' has no attribute '_C' (most likely due to a circular import)

**Comment by DreamLoveBetty** [comment]
I am using the plugin version of Confy, but I also encountered the same error because other plugins require "Triton". Redeploying a new Confy plugin does not allow "Triton" to function properly. Have you solved this problem?

**Comment by Torcelllo** [comment]
It seems to function OK even without Triton

**Comment by sipie800** [comment]
same here
