### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.50 GiB. GPU

### ISSUE THREAD

**Issue by xhoxye** [lllyasviel/Omost#21]
2070S-8G，
![QQ截图20240602063228](https://github.com/lllyasviel/Omost/assets/129571231/df20492f-da25-47e2-8eac-8d376c12831a)
`
Unload to CPU: CLIPTextModel
Load to GPU: UNet2DConditionModel
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:19<00:00,  1.05it/s]
Unload to CPU: UNet2DConditionModel
Load to GPU: AutoencoderKL
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\gradio\queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\gradio\blocks.py", line 1908, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\gradio\blocks.py", line 1485, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\gradio\utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\Omost\Omost\gradio_app.py", line 235, in diffusion_fn
    pixels = vae.decode(latents).sample
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 303, in decode
    decoded = self._decode(z, return_dict=False)[0]
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 276, in _decode
    dec = self.decoder(z)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\diffusers\models\autoencoders\vae.py", line 337, in forward
    sample = up_block(sample, latent_embeds)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 2750, in forward
    hidden_states = upsampler(hidden_states)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\diffusers\models\upsampling.py", line 180, in forward
    hidden_states = self.conv(hidden_states)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\ProgramData\anaconda3\envs\omost\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.50 GiB. GPU
`

**Comment by xhoxye** [comment]
512 is OK, 1024 is not
![QQ截图20240602100839](https://github.com/lllyasviel/Omost/assets/129571231/a62e8540-0bae-4ec9-a0a2-9a89d0b373d8)
