### ISSUE TITLE
Trying to run locally but I`ve got an error instantly on generation

### ISSUE THREAD

**Issue by Antonius-ui** [lllyasviel/Omost#7]
(omost) D:\Omost>python gradio_app.py
D:\Omost\lib_omost\pipeline.py:64: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  alphas_cumprod = torch.tensor(np.cumprod(alphas, axis=0), dtype=torch.float32)
Unload to CPU: CLIPTextModel
Unload to CPU: CLIPTextModel
Unload to CPU: UNet2DConditionModel
Unload to CPU: AutoencoderKL
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.31s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
You shouldn't move a model that is dispatched using accelerate hooks.
Unload to CPU: LlamaForCausalLM
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
You shouldn't move a model that is dispatched using accelerate hooks.
Load to GPU: LlamaForCausalLM
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Exception in thread Thread-11 (generate):
Traceback (most recent call last):
  File "C:\Users\X\.conda\envs\omost\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\X\.conda\envs\omost\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\X\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\transformers\generation\utils.py", line 1758, in generate
    result = self._sample(
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\transformers\generation\utils.py", line 2397, in _sample
    outputs = self(
  File "C:\Users\X\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1164, in forward
    outputs = self.model(
  File "C:\Users\X\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\transformers\models\llama\modeling_llama.py", line 940, in forward
    causal_mask = self._update_causal_mask(
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1061, in _update_causal_mask
    causal_mask = torch.triu(causal_mask, diagonal=1)
RuntimeError: "triu_tril_cuda_template" not implemented for 'BFloat16'
Traceback (most recent call last):
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\gradio\queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\gradio\blocks.py", line 1908, in process_api
    result = await self.call_function(
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\gradio\blocks.py", line 1497, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\gradio\utils.py", line 632, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\gradio\utils.py", line 758, in asyncgen_wrapper
    response = await iterator.__anext__()
  File "D:\Omost\chat_interface.py", line 554, in _stream_fn
    first_response, first_interrupter = await async_iteration(generator)
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\gradio\utils.py", line 632, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\gradio\utils.py", line 625, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\gradio\utils.py", line 608, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\X\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "D:\Omost\gradio_app.py", line 164, in chat_fn
    for text in streamer:
  File "C:\Users\X\.conda\envs\omost\lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "C:\Users\X\.conda\envs\omost\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
Last assistant response is not valid canvas: expected string or bytes-like object

**Comment by Bocchi-Chan2023** [comment]
write your pc environment first

**Comment by Antonius-ui** [comment]
> pc environment
I`m sry, can you clarify a bit? If we're talking about PC characteristics then:
GeForce RTX 4070, Intel i5-13500, 32Gb Ram, Win11. Smooth running Auto1111 and Comfy with SDXL models etc, no problem at all

**Comment by EvilBT** [comment]
I also encountered the same problem, running environment: windows11, 32G ram, 2080 8G GPU, python3.10.11 pytorch 2.2.2+cu121. Currently stable and reproducible, steps to reproduce: the first time you enter the prompt, there is no problem, wait for llm to reply, click render the Image!, the raw image is normal, then enter any prompt again, click submit and the above bug will appear (from Google Translate)

**Comment by hutaiHang** [comment]
> RuntimeError: "triu_tril_cuda_template" not implemented for 'BFloat16'

This problem can be solved by https://huggingface.co/meta-llama/Meta-Llama-3-8B/discussions/34#:~:text=I%20solved%20my%20problem%20by%20replacing

**Comment by TraceIvan** [comment]
> I also encountered the same problem, running environment: windows11, 32G ram, 2080 8G GPU, python3.10.11 pytorch 2.2.2+cu121. Currently stable and reproducible, steps to reproduce: the first time you enter the prompt, there is no problem, wait for llm to reply, click render the Image!, the raw image is normal, then enter any prompt again, click submit and the above bug will appear (from Google Translate)我也遇到了同样的问题，运行环境：windows 11，32 G内存，2080 8 G GPU，python3.10.11 pytorch 2.2.2+ cu 121。目前稳定可复制，复制步骤：第一次进入提示，没有问题，等待llm回复，点击渲染图片！，原始图像是正常的，然后再次输入任何提示，点击提交，上述错误将出现（从谷歌翻译）

I have the same problem. The first time I generate the image prompt and render the image, it is ok. Then, when I continue to enter the modification requirements in the same session, I will get an error: "raise Empty". My environment：windows 10，Python 3.10.13，torch 2.1.0+cu118，RTX 2070 8G.
![image](https://github.com/lllyasviel/Omost/assets/27859479/362a8baa-17b2-4d0b-bb48-da642414d6df)
